---
title: "Analyzing COVID19 in USA"
description: |
  Analyzing Covid 19 reports
author:
  - name: Ardalan Mirshani
    affiliation: Novartis
    url: https://mirshani.com
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    self_contained: false
packages: [ggplot2, forcats]
categories: [Visualization, Modeling]
tech: [R, SqL, Python]
# preview: images/sharpe-ratio.png
bibliography: bibliography.bib
draft: false
# slug: ???
---

::: {.l-page}
```{r, child= here::here("_assets", "article_header.Rmd")}
```

::: {.panelset}
::: {.panel}
#### 🟣 Intro

[@uber_technologies_inc_uber_2020]

<!-- LikeBtn.com BEGIN -->

```{=html}
<script>(function(d,e,s){if(d.getElementById("likebtn_wjs"))return;a=d.createElement(e);m=d.getElementsByTagName(e)[0];a.async=1;a.id="likebtn_wjs";a.src=s;m.parentNode.insertBefore(a, m)})(document,"script","//w.likebtn.com/js/w/widget.js");</script>
```
<!-- LikeBtn.com END -->
:::

::: {.panel}
#### 🔵 Data
```{r, layout="l-screen"}
library(rmarkdown)
paged_table(mtcars)
```
:::

::: {.panel}
#### 🟢 Cleaning
```{r, eval = F, echo = T}
starwars %>%
  filter(!is.na(species)) %>%
  mutate(species = fct_lump(species, n = 3)) %>%
  count(species)
```
:::

::: {.panel}
#### 🟢 Cleaning
```{r}
library(reticulate)
```


```{python}
print("Hello Python!")
x = [1, 2, 3]
x
```
:::

::: {.panel}
#### 🟠 Modeling
```{python, echo=T, eval=F}
import matplotlib.pyplot as plt
import numpy as np
t = 1 + np.arange(0, 2, 0.01)
s = 1 + np.sin(2*np.pi*t)
plt.plot(t,s)
plt.show()
```
:::


::: {.panel}
#### 🔴 Visualization
```{r, echo=F, out.width="50%"}
library(ggplot2)
ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width, col = Species)) +
  geom_point() +
  labs(title = "A Nice Iris Dataset Graphic", x = "Sepal Length", y = "Sepal Width") +
  theme_minimal()
```
:::

::: {.panel}
#### 🔴 Visualization
```{r, preview = T, out.width="50%"}
ggplot(diamonds) + geom_point(aes(x=carat, y=price, color=cut)) + geom_smooth(aes(x=carat, y=price, color=cut)) # Same as above but specifying the aesthetics inside the geoms.
```
:::


:::
:::
